#欢迎使用 Materialis 主题
#主题作者：W-Can1425 system:error
#Comment 请选择一个
#---start---
comment:
  service: twikoo  # 可选: twikoo, waline, giscus
twikoo:
  envId: https://pinglun.yizhixiaozhu.top # 腾讯云环境ID,vercel填写域名
  lang: zh-CN # 语言，支持 'zh-CN', 'en'
waline:
  serverURL: your_server_url # 填写你的 Waline 服务器地址
  lang: zh-CN # 语言，支持 'zh-CN', 'en'
giscus:
  repo: your_repo # 你的 GitHub 仓库，格式为 username/repo
  repoId: your_repo_id # 你的 GitHub 仓库ID
  category: your_category # 你的 GitHub Discussions 分类
  categoryId: your_category_id # 你的 GitHub Discussions 分类ID
  mapping: pathname # 映射方式，支持 'url', 'title', 'og:title', 'specific'
  reactionsEnabled: true # 是否启用表情反应
  emitMetadata: false # 是否发送元数据
  inputPosition: bottom # 输入框位置，支持 'top', 'bottom'
  lang: zh-CN # 语言，支持 'zh-CN', 'en'
#---end---
# 侧边栏配置
#---start---
sidebar:
  # 用户信息
  name: "system:error"
  slogen: "长风破浪会有时，直挂云帆济沧海。"
  avatar: "https://blog.yizhixiaozhu.top/images/1.png"
# 导航菜单
nav:
  - name: "首页"
    icon: "home"
    url: "/"
    
  - name: "文章归档"
    icon: "article"
    url: "/diary/"
    
  - name: "分类"
    icon: "category"
    url: "/categories/"
    
  - name: "标签"
    icon: "tag"
    url: "/tags/"
    
  - name: "关于"
    icon: "person"
    url: "/about/"

  - name: "友链"
    icon: "link"
    url: "/links/"

  - name: "说说"
    icon: "chat"
    url: "/shuoshuo/"
#---end---
#友链配置
#---start---
links:
  use: 2 # 0关闭友链 1使用qexo友链 2使用主题友链
  qexo:
    url: https://qexo.blog.yizhixiaozhu.top #填写你qexo的地址
#---end--- 
#颜色设置
#---start---
color:
  main: "#d9e2ff"
#--end---
#自定义代码
#---start---
# 自定义资源文件配置
custom:
  # 自定义 CSS 文件
  # css:
  #   - /css/custom.css
  #   - /css/user-style.css
  #   - https://cdn.example.com/external.css
  
  # 自定义 JavaScript 文件
  # js:
  #   - /js/custom.js
  #   - /js/user-script.js
  #   - https://cdn.example.com/external.js
  
  # 自定义头部代码
  # head: |

  #   <!-- 自定义 meta 标签或其他 head 内容 -->
  #   <meta name="custom-meta" content="value">
  
  # 自定义底部代码
  # footer: |
  #   <!-- 自定义统计代码等 -->
  #   <script>
  #     console.log('自定义脚本');
  #   </script>
#---end---
#字体设置
#---start---
font:
  primary: lxwk  # 只能选择一个: lxwk  dingtalk pingfang 或者false
#---end---
#Footer
#---start---
# Footer 配置
footer:
  # 版权信息
  copyright: "保留所有权利"
  
  # 备案信息（中国用户）
  beian:
    icp: "京ICP备12345678号"
    ps: "京公网安备 12345678901234号"
  
  # 主题名称
  theme_name: "Materialis"
  
  # 自定义徽章
  # badges:
  #   - text: "开源"
  #     variant: "small"
  #     icon: "code"
  #     href: "https://github.com/yourname/your-theme"
    
  #   - text: "v1.0.0"
  #     variant: "small"
  #     icon: "tag"
    
  #   - text: "在线"
  #     variant: "small"
  #     icon: "wifi"
#---end---
#说说
#---start---
shuoshuo:
  use: 2 # 0关闭说说 1使用qexo说说 2使用主题说说
  qexo:
    url: https://qexo.blog.yizhixiaozhu.top #填写你qexo的地址
banner:
  title: "Materialis"
  subtitle: "一个基于Hexo的静态博客主题"
#---end---
#纪念日设置
#---start---
memorial_days:
  enable: true  # 是否启用纪念日黑白效果
  dates:  # 纪念日日期列表 (月-日格式)
    - 7.7
    - 9.18
    - 12.13
#---end---